# Generated by Django 2.1 on 2018-08-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-order', 'title'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
    ]
