# Generated by Django 2.1 on 2018-08-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20180826_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threads',
            options={'ordering': ['updated']},
        ),
        migrations.AddField(
            model_name='threads',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
