# Generated by Django 2.0.2 on 2018-09-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20180826_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threads',
            options={'ordering': ['-updated']},
        ),
    ]
